#!/usr/bin/env python3

# GS-Shapley Algorithm
# Created by: Akshay Singh and
# Date: 09/20/2017
# Purpose: Run gs1.py and paste the output in data.txt
#          that would help to plot the graph
#          
# INPUT(S): None
# OUTPUT(S): Paste into data.txt and call gnuplot
# EXAMPLES: Model.gpt output


import sys
import subprocess


numberList = [1000,1500,2000,2500,3000,3500,4000,4500,5000]
data = open("data.txt","w")
for i in numberList:
	subprocess.call(["./gs1.py", str(i)], stdout=data)
data.close()
subprocess.call(["/usr/bin/gnuplot -persist model.gpt"], shell=True)



